// This file is generated by Slice Machine. Update with care!

import DownloadSection from './DownloadSection';

export {
	DownloadSection,
};

export const components = {
	download_section: DownloadSection,
};
